# Generated by Django 3.2.1 on 2021-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='hospital_id',
        ),
    ]
