# Generated by Django 3.2.1 on 2021-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='updated_at',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='images',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
