# Generated by Django 3.2.1 on 2021-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_bed',
            name='available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
