# Generated by Django 3.2.1 on 2021-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210515_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
