# Generated by Django 3.2.1 on 2021-05-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oxygencylinders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='death_count',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='discharge_count',
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.CreateModel(
            name='discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.IntegerField()),
                ('total', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.IntegerField()),
                ('total', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospitals')),
            ],
        ),
    ]
