# Generated by Django 3.2.1 on 2021-05-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hospitals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
