# Generated by Django 3.2.1 on 2021-05-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210504_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icu_bed',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='normal_bed',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='ventilators',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='icu_bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.icu_bed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='normal_bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.normal_bed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='ventilators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ventilators'),
            preserve_default=False,
        ),
    ]
