# Generated by Django 3.2.1 on 2021-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hospitals_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
