# Generated by Django 3.2.1 on 2021-05-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210504_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='icu_bed',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='normal_bed',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='ventilators',
        ),
        migrations.AddField(
            model_name='icu_bed',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hospitals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normal_bed',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hospitals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventilators',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hospitals'),
            preserve_default=False,
        ),
    ]
