# Generated by Django 3.2.1 on 2021-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
